// Loader for the static college dataset produced by scripts/build-colleges.
// data/colleges.json is generated separately; this module only types and
// sanity-checks it. Keep all matching logic in lib/match.ts.

import rawColleges from "@/data/colleges.json";
import type { College } from "./types";

// Lightweight structural check run against the first row only. The dataset is
// generated by our own pipeline, so this guards against a stale or malformed
// build, not against arbitrary input.
function hasCollegeShape(row: unknown): row is College {
  if (typeof row !== "object" || row === null) {
    return false;
  }
  const candidate = row as Record<string, unknown>;
  return (
    typeof candidate.unitId === "number" &&
    typeof candidate.name === "string" &&
    typeof candidate.state === "string" &&
    typeof candidate.programShares === "object" &&
    candidate.programShares !== null
  );
}

export function getColleges(): College[] {
  const rows = rawColleges as unknown;
  if (Array.isArray(rows) === false) {
    throw new Error("data/colleges.json must contain a JSON array of college rows");
  }
  const list = rows as unknown[];
  if (list.length > 0 && hasCollegeShape(list[0]) === false) {
    throw new Error("data/colleges.json rows do not match the College contract; regenerate the dataset");
  }
  return list as College[];
}
