// Sample report used only for local visual development (the "Preview sample
// report" button). Stats are plausible approximations of real College
// Scorecard data, not live values.

import type { Report, ScoredCollege, StudentProfile } from "./types";

const sampleProfile: StudentProfile = {
  name: "John Smith",
  gpa: 3.5,
  satTotal: 1230,
  actComposite: null,
  interests: ["computer-science"],
  homeState: "PA",
  prefersNearHome: true,
  prefersWarmClimate: false,
  sizePreference: null,
  learningStyle: "hands-on",
  needsFinancialAid: false,
  narrativeHighlights: [
    "Won the Congressional App Challenge for Pennsylvania",
    "AP Computer Science A score of 5",
    "AP Calculus BC score of 4",
  ],
};

const reach: ScoredCollege[] = [
  {
    college: {
      unitId: 211440,
      name: "Carnegie Mellon University",
      city: "Pittsburgh",
      state: "PA",
      control: "private",
      admitRate: 0.11,
      satReading25: 720,
      satReading75: 770,
      satMath25: 780,
      satMath75: 800,
      satAvg: 1530,
      actComposite25: 34,
      actComposite75: 35,
      actCompositeMid: 35,
      tuitionInState: 63829,
      tuitionOutOfState: 63829,
      avgNetPrice: 32832,
      undergradSize: 7509,
      locale: 12,
      gradRate: 0.9,
      medianEarnings10yr: 99998,
      programShares: { pcip11: 0.17, pcip14: 0.22, pcip52: 0.09 },
    },
    bucket: "reach",
    score: 62,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 sits below the 1500-1570 middle band",
        points: 12,
      },
      {
        label: "Program strength",
        detail: "17 percent of degrees are in computer science",
        points: 30,
      },
      {
        label: "Preference fit",
        detail: "In-state and known for project-based CS work",
        points: 20,
      },
    ],
    rationale:
      "One of the strongest computer science programs in the country, in-state in Pittsburgh. An 11 percent admit rate makes it a long shot, but the App Challenge win is the kind of signal its admissions team looks for.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 213543,
      name: "Lehigh University",
      city: "Bethlehem",
      state: "PA",
      control: "private",
      admitRate: 0.26,
      satReading25: 640,
      satReading75: 710,
      satMath25: 680,
      satMath75: 770,
      satAvg: 1400,
      actComposite25: 31,
      actComposite75: 34,
      actCompositeMid: 32,
      tuitionInState: 62180,
      tuitionOutOfState: 62180,
      avgNetPrice: 35275,
      undergradSize: 5764,
      locale: 13,
      gradRate: 0.88,
      medianEarnings10yr: 92224,
      programShares: { pcip11: 0.08, pcip14: 0.31, pcip52: 0.28 },
    },
    bucket: "reach",
    score: 58,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 is under the 1320-1480 middle band",
        points: 14,
      },
      {
        label: "Program strength",
        detail: "Engineering-heavy school with strong applied CS",
        points: 24,
      },
      {
        label: "Preference fit",
        detail: "About an hour from most of eastern Pennsylvania",
        points: 20,
      },
    ],
    rationale:
      "A hands-on engineering culture about an hour from home, with computer science inside a top applied program. Test scores land below the typical admit, so treat it as a reach worth one strong application.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 215293,
      name: "University of Pittsburgh",
      city: "Pittsburgh",
      state: "PA",
      control: "public",
      admitRate: 0.5,
      satReading25: 630,
      satReading75: 700,
      satMath25: 620,
      satMath75: 720,
      satAvg: 1330,
      actComposite25: 28,
      actComposite75: 33,
      actCompositeMid: 31,
      tuitionInState: 20154,
      tuitionOutOfState: 38928,
      avgNetPrice: 27509,
      undergradSize: 20220,
      locale: 12,
      gradRate: 0.84,
      medianEarnings10yr: 62098,
      programShares: { pcip11: 0.09, pcip14: 0.12, pcip26: 0.14 },
    },
    bucket: "reach",
    score: 55,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 trails the 1250-1420 middle band",
        points: 16,
      },
      {
        label: "Program strength",
        detail: "Growing computing school with co-op options",
        points: 19,
      },
      {
        label: "Preference fit",
        detail: "In-state public tuition in a walkable city campus",
        points: 20,
      },
    ],
    rationale:
      "In-state public pricing with a solid computing school and real co-op pipelines into Pittsburgh tech. Scores sit just under the middle band, so it is a realistic reach rather than a long shot.",
    rationaleSource: "gemini",
  },
];

const target: ScoredCollege[] = [
  {
    college: {
      unitId: 214777,
      name: "Penn State University Park",
      city: "University Park",
      state: "PA",
      control: "public",
      admitRate: 0.55,
      satReading25: 590,
      satReading75: 670,
      satMath25: 590,
      satMath75: 700,
      satAvg: 1270,
      actComposite25: 26,
      actComposite75: 32,
      actCompositeMid: 29,
      tuitionInState: 19835,
      tuitionOutOfState: 38651,
      avgNetPrice: 29906,
      undergradSize: 41745,
      locale: 13,
      gradRate: 0.85,
      medianEarnings10yr: 60600,
      programShares: { pcip11: 0.07, pcip14: 0.16, pcip52: 0.17 },
    },
    bucket: "target",
    score: 71,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 lands inside the 1180-1370 middle band",
        points: 26,
      },
      {
        label: "Program strength",
        detail: "Large engineering and IST colleges with many CS paths",
        points: 22,
      },
      {
        label: "Preference fit",
        detail: "In-state flagship a few hours from any part of PA",
        points: 23,
      },
    ],
    rationale:
      "The in-state flagship where a 1230 sits comfortably in the admitted range. Multiple computing majors across engineering and IST give room to pick a practical track once he arrives.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 212054,
      name: "Drexel University",
      city: "Philadelphia",
      state: "PA",
      control: "private",
      admitRate: 0.8,
      satReading25: 600,
      satReading75: 690,
      satMath25: 590,
      satMath75: 700,
      satAvg: 1290,
      actComposite25: 26,
      actComposite75: 32,
      actCompositeMid: 29,
      tuitionInState: 58965,
      tuitionOutOfState: 58965,
      avgNetPrice: 42160,
      undergradSize: 12482,
      locale: 11,
      gradRate: 0.71,
      medianEarnings10yr: 68467,
      programShares: { pcip11: 0.13, pcip14: 0.18, pcip51: 0.16 },
    },
    bucket: "target",
    score: 74,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 is inside the 1190-1390 middle band",
        points: 25,
      },
      {
        label: "Program strength",
        detail: "13 percent of degrees in computing, co-op required",
        points: 27,
      },
      {
        label: "Preference fit",
        detail: "Philadelphia campus built around work-integrated learning",
        points: 22,
      },
    ],
    rationale:
      "Built around a mandatory co-op, so he would graduate with up to 18 months of paid programming work. As hands-on as a CS degree gets, and Philadelphia keeps him close to home.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 195003,
      name: "Rochester Institute of Technology",
      city: "Rochester",
      state: "NY",
      control: "private",
      admitRate: 0.71,
      satReading25: 600,
      satReading75: 690,
      satMath25: 610,
      satMath75: 720,
      satAvg: 1310,
      actComposite25: 27,
      actComposite75: 33,
      actCompositeMid: 30,
      tuitionInState: 56294,
      tuitionOutOfState: 56294,
      avgNetPrice: 38095,
      undergradSize: 13711,
      locale: 21,
      gradRate: 0.7,
      medianEarnings10yr: 65198,
      programShares: { pcip11: 0.21, pcip14: 0.19, pcip50: 0.11 },
    },
    bucket: "target",
    score: 72,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 is inside the 1210-1410 middle band",
        points: 24,
      },
      {
        label: "Program strength",
        detail: "21 percent of degrees in computing disciplines",
        points: 28,
      },
      {
        label: "Preference fit",
        detail: "Co-op model, though Rochester is a longer drive",
        points: 20,
      },
    ],
    rationale:
      "One of the highest shares of computing degrees on this list, with a co-op program that matches his practical bent. The tradeoff is distance: Rochester is farther than the Pennsylvania options.",
    rationaleSource: "fallback",
  },
];

const likely: ScoredCollege[] = [
  {
    college: {
      unitId: 216339,
      name: "Temple University",
      city: "Philadelphia",
      state: "PA",
      control: "public",
      admitRate: 0.8,
      satReading25: 580,
      satReading75: 670,
      satMath25: 560,
      satMath75: 670,
      satAvg: 1240,
      actComposite25: 25,
      actComposite75: 31,
      actCompositeMid: 28,
      tuitionInState: 20851,
      tuitionOutOfState: 34576,
      avgNetPrice: 24106,
      undergradSize: 22078,
      locale: 11,
      gradRate: 0.75,
      medianEarnings10yr: 55098,
      programShares: { pcip11: 0.06, pcip52: 0.22, pcip09: 0.11 },
    },
    bucket: "likely",
    score: 78,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 is above the 1140-1340 middle band",
        points: 30,
      },
      {
        label: "Program strength",
        detail: "Accredited CS program inside a big public university",
        points: 22,
      },
      {
        label: "Preference fit",
        detail: "In-state tuition in Philadelphia, close to home",
        points: 26,
      },
    ],
    rationale:
      "His scores sit above the typical admit, and in-state tuition in Philadelphia keeps cost and distance down. A dependable yes with a legitimate CS department.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 216764,
      name: "West Chester University of Pennsylvania",
      city: "West Chester",
      state: "PA",
      control: "public",
      admitRate: 0.88,
      satReading25: 540,
      satReading75: 630,
      satMath25: 530,
      satMath75: 610,
      satAvg: 1160,
      actComposite25: 22,
      actComposite75: 27,
      actCompositeMid: 25,
      tuitionInState: 11444,
      tuitionOutOfState: 22738,
      avgNetPrice: 21422,
      undergradSize: 14615,
      locale: 21,
      gradRate: 0.74,
      medianEarnings10yr: 52471,
      programShares: { pcip11: 0.05, pcip13: 0.12, pcip52: 0.16 },
    },
    bucket: "likely",
    score: 76,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 clears the 1070-1240 middle band",
        points: 31,
      },
      {
        label: "Program strength",
        detail: "Small CS department with close faculty contact",
        points: 18,
      },
      {
        label: "Preference fit",
        detail: "Lowest sticker price on the list, suburban PA",
        points: 27,
      },
    ],
    rationale:
      "The value pick: state-system tuition under half of most options here, close to home, with a CS program small enough that professors know every student by name.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 212106,
      name: "Duquesne University",
      city: "Pittsburgh",
      state: "PA",
      control: "private",
      admitRate: 0.9,
      satReading25: 560,
      satReading75: 650,
      satMath25: 550,
      satMath75: 640,
      satAvg: 1200,
      actComposite25: 23,
      actComposite75: 29,
      actCompositeMid: 26,
      tuitionInState: 46728,
      tuitionOutOfState: 46728,
      avgNetPrice: 33067,
      undergradSize: 5251,
      locale: 12,
      gradRate: 0.79,
      medianEarnings10yr: 58452,
      programShares: { pcip11: 0.04, pcip51: 0.24, pcip52: 0.19 },
    },
    bucket: "likely",
    score: 70,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 clears the 1110-1290 middle band",
        points: 29,
      },
      {
        label: "Program strength",
        detail: "Smaller CS offering with strong advising",
        points: 15,
      },
      {
        label: "Preference fit",
        detail: "Mid-size private campus in downtown Pittsburgh",
        points: 26,
      },
    ],
    rationale:
      "A smaller Pittsburgh campus where his numbers are safely above the typical admit. CS is not the headline program, but class sizes stay small and the city has internships.",
    rationaleSource: "gemini",
  },
  {
    college: {
      unitId: 216010,
      name: "Susquehanna University",
      city: "Selinsgrove",
      state: "PA",
      control: "private",
      admitRate: 0.82,
      satReading25: 550,
      satReading75: 650,
      satMath25: 540,
      satMath75: 640,
      satAvg: 1190,
      actComposite25: 23,
      actComposite75: 29,
      actCompositeMid: 26,
      tuitionInState: 56290,
      tuitionOutOfState: 56290,
      avgNetPrice: 30887,
      undergradSize: 2237,
      locale: 32,
      gradRate: 0.73,
      medianEarnings10yr: 55794,
      programShares: { pcip11: 0.05, pcip52: 0.27, pcip26: 0.1 },
    },
    bucket: "likely",
    score: 68,
    components: [
      {
        label: "Academic fit",
        detail: "SAT 1230 clears the 1090-1290 middle band",
        points: 28,
      },
      {
        label: "Program strength",
        detail: "Liberal-arts CS with required real-world capstone",
        points: 14,
      },
      {
        label: "Preference fit",
        detail: "Central Pennsylvania, two hours from most of the state",
        points: 26,
      },
    ],
    rationale:
      "A small central-PA option where he would be a strong admit and likely merit-aid candidate. Every student completes an off-campus or applied capstone, which suits a builder.",
    rationaleSource: "gemini",
  },
];

export const sampleReport: Report = {
  profile: sampleProfile,
  generatedAt: "2026-09-01T15:30:00.000Z",
  reach,
  target,
  likely,
};
